/** Seed catalog: names, CAS, formula, category, grade, short commercial blurb + optional specs */
export const SEED_CHEMICALS = [
  {
    name: 'Potassium Chloride',
    casNumber: '7447-40-7',
    formula: 'KCl',
    category: 'CHEMICALS',
    grade: 'Drilling',
    description:
      'Workhorse weighting and shale-stabilising salt for KCl/polymer muds — predictable density build without harsh chlorides load on sensitive formations.',
    viscosity: '1.03 CP',
    purity: '98.5%',
    freezingPoint: '-11.2°C',
  },
  {
    name: 'Sodium Chloride',
    casNumber: '7647-14-5',
    formula: 'NaCl',
    category: 'CHEMICALS',
    grade: 'Drilling',
    description:
      'Economical brine base and crystallisation control for saturated systems; pairs cleanly with polymers and lubricants.',
    viscosity: '—',
    purity: '99.0%',
    freezingPoint: '—',
  },
  {
    name: 'Calcium Chloride',
    casNumber: '10043-52-4',
    formula: 'CaCl2',
    category: 'CHEMICALS',
    grade: 'Technical',
    description:
      'Dense brine component and drying agent; boosts water-phase salinity for shale inhibition and completion dewatering.',
    viscosity: '—',
    purity: '94–98%',
    freezingPoint: '—',
  },
  {
    name: 'Calcium Bromide',
    casNumber: '7789-41-5',
    formula: 'CaBr2',
    category: 'CHEMICALS',
    grade: 'Completion',
    description:
      'High-density clear brines for completion and workover — minimal solids, compatible with packer fluids and resin systems.',
    viscosity: '—',
    purity: '—',
    freezingPoint: '—',
  },
  {
    name: 'Soda Ash',
    casNumber: '497-19-8',
    formula: 'Na2CO3',
    category: 'CHEMICALS',
    grade: 'Industrial',
    description:
      'Softens make-up water, trims hardness, and helps pH/alkalinity control in dispersed and polymer muds.',
    viscosity: '—',
    purity: '99.2%',
    freezingPoint: '—',
  },
  {
    name: 'Caustic Soda',
    casNumber: '1310-73-2',
    formula: 'NaOH',
    category: 'CHEMICALS',
    grade: 'Industrial',
    description:
      'Fast alkalinity lift for pH management, lignosulfonate systems, and contaminant treatment on active mud circuits.',
    viscosity: '—',
    purity: '99.0%',
    freezingPoint: '318°C',
  },
  {
    name: 'Xanthan Gum',
    casNumber: '11138-66-2',
    formula: '—',
    category: 'CHEMICALS',
    grade: 'Technical',
    description:
      'Shear-thinning viscosifier for water-based fluids — carries cuttings at low pump rates, breaks cleanly downhole.',
    viscosity: 'High',
    purity: '—',
    freezingPoint: '—',
  },
  {
    name: 'XCD Polymer',
    casNumber: '—',
    formula: '—',
    category: 'CHEMICALS',
    grade: 'Drilling',
    description:
      'Biopolymer for elevated low-shear viscosity — improves suspension in high-solids and high-angle intervals.',
    viscosity: 'High',
    purity: '—',
    freezingPoint: '—',
  },
  {
    name: 'CMC HV',
    casNumber: '9000-11-7',
    formula: '—',
    category: 'CHEMICALS',
    grade: 'Technical',
    description:
      'High-viscosity carboxymethyl cellulose for fluid-loss control and filtration cake quality in water-based muds.',
    viscosity: '—',
    purity: '—',
    freezingPoint: '—',
  },
  {
    name: 'HEC Liquid',
    casNumber: '9004-62-0',
    formula: '—',
    category: 'CHEMICALS',
    grade: 'Technical',
    description:
      'Liquid hydroxyethyl cellulose for easy field mixing — viscosifies brines and completion fluids without dusting.',
    viscosity: '—',
    purity: '—',
    freezingPoint: '—',
  },
  {
    name: 'Organophylic Clay',
    casNumber: '—',
    formula: '—',
    category: 'CHEMICALS',
    grade: 'Oil-based',
    description:
      'Gelling agent for oil/synthetic systems — builds structure for suspension and barite sag resistance.',
    viscosity: '—',
    purity: '—',
    freezingPoint: '—',
  },
  {
    name: 'Monoethylene Glycol (MEG)',
    casNumber: '107-21-1',
    formula: 'C2H6O2',
    category: 'CHEMICALS',
    grade: 'Technical',
    description:
      'Hydrate suppression and freeze protection in pipelines, bundles, and process loops — predictable cryoscopic behaviour.',
    viscosity: '16.1 CP',
    purity: '99.0%',
    freezingPoint: '-13°C',
  },
  {
    name: 'Diethylene Glycol (DEG)',
    casNumber: '111-46-6',
    formula: 'C4H10O3',
    category: 'CHEMICALS',
    grade: 'Technical',
    description:
      'Higher-boiling glycol for dehydration and hydrate risk reduction where MEG volatility is a concern.',
    viscosity: '—',
    purity: '99.0%',
    freezingPoint: '—',
  },
  {
    name: 'Triethylene Glycol (TEG)',
    casNumber: '112-27-6',
    formula: 'C6H14O4',
    category: 'CHEMICALS',
    grade: 'Technical',
    description:
      'Dehydration workhorse for gas sweetening trains and offshore dehydration skids - low carryover when specd correctly.',
    viscosity: '—',
    purity: '99.0%',
    freezingPoint: '—',
  },
  {
    name: 'THPS 75%',
    casNumber: '55566-30-8',
    formula: 'C8H24O12P2S',
    category: 'CHEMICALS',
    grade: 'Biocide',
    description:
      'Broad-spectrum sulphur-based biocide for sulphate-reducing bacteria control in water floods and mud systems.',
    viscosity: '—',
    purity: '75% soln.',
    freezingPoint: '—',
  },
  {
    name: 'Emulsifiers Package',
    casNumber: '—',
    formula: 'Blend',
    category: 'CHEMICALS',
    grade: 'OBM/SBM',
    description:
      'Primary/secondary emulsifier blends for stable oil/synthetic muds — tight emulsion, low HPHT filtrate.',
    viscosity: '—',
    purity: '—',
    freezingPoint: '—',
  },
  {
    name: 'Xylene',
    casNumber: '1330-20-7',
    formula: 'C8H10',
    category: 'CHEMICALS',
    grade: 'Solvent',
    description:
      'Aromatic solvent for degrease, flush, and spotting applications — use with HSE controls and ventilation.',
    viscosity: '—',
    purity: 'Mixed isomers',
    freezingPoint: '—',
  },
];
